name: shared
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  app:
    path: ../app
  translations:
    path: ../translations
  admin_portal:
    path: ../admin_portal
  fire_portal:
    path: ../fire_portal

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  provider: ^6.1.4
  http: ^1.2.2
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.16
  flutter_easyloading: ^3.0.5
  carousel_slider: ^5.0.0
  animate_do: ^4.2.0
  scrollable_positioned_list: ^0.3.8
  google_sign_in: ^6.3.0
  crypto: ^3.0.6
  sign_in_with_apple: ^6.1.4
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.8
  geolocator: ^13.0.4
  uuid: ^4.5.1
  google_maps_flutter: ^2.12.1
  path: ^1.9.0
  path_provider: ^2.1.5
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  hexcolor: ^3.0.1
  flutter_rating_bar: ^4.0.1
  flutter_html: ^3.0.0
  algoliasearch: ^1.30.2
  algolia_helper_flutter: ^1.2.0
  melos: ^6.0.0
  google_fonts: ^6.2.1
  timelines_plus: ^1.0.6
  easy_radio: ^0.0.3
  image_picker: ^1.1.2
  auto_size_text: ^3.0.0
  loading_animation_widget: ^1.3.0
  flutter_svg_provider: ^1.0.7
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  rxdart: ^0.28.0
  go_router: ^15.1.0
  flutter_quill: ^11.2.0
  flutter_quill_delta_from_html: ^1.4.1
  vsc_quill_delta_to_html: ^1.0.5
  url_strategy: ^0.2.0
  file_picker: ^10.2.0
  open_file: ^3.5.10
  syncfusion_flutter_pdfviewer: ^30.1.37
  font_awesome_flutter:
    git:
      url: https://github.com/kawad852/font_awesome_flutter.git

  #firebase
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_messaging: ^15.2.5
  firebase_analytics: ^11.4.5
  firebase_ui_firestore: ^1.7.1
  firebase_storage: ^12.4.5
  cloud_functions: ^5.4.0
  flutter_local_notifications: ^19.1.0


dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  go_router_builder: ^2.9.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/android_launcher.png"
  image_path_ios: "assets/ios_launcher.png"

flutter_native_splash:
  color: "#131E2A"
  image: ../../assets/android_12_splash.png
  android: true
  ios: true
  android_12:
    image: ../../assets/android_12_splash.png
    color: "#131E2A"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - ../../assets/
    - ../../assets/images/
    - ../../assets/icons/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
