// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw9Kht69x9dr4goEPqJ8p8PNyWkiBk-8k',
    appId: '1:1063729292121:web:7169811ce8c9d6f1826248',
    messagingSenderId: '1063729292121',
    projectId: 'imtithal-app',
    authDomain: 'imtithal-app.firebaseapp.com',
    storageBucket: 'imtithal-app.firebasestorage.app',
    measurementId: 'G-TT32VFK3TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXTGxtq3npm8rU9fbyHd-XNBdyhnMEvVc',
    appId: '1:1063729292121:android:b2c600a94302757f826248',
    messagingSenderId: '1063729292121',
    projectId: 'imtithal-app',
    storageBucket: 'imtithal-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPmqpxv-3hm2wKOrIX630DtBFYTZHJLss',
    appId: '1:1063729292121:ios:40b39e9ed60d0419826248',
    messagingSenderId: '1063729292121',
    projectId: 'imtithal-app',
    storageBucket: 'imtithal-app.firebasestorage.app',
    iosBundleId: 'com.imtithal.wecan',
  );

}