class MyIcons {
  static const String _path = 'assets/icons/';

  static const String logo = '${_path}logo.svg';
  static const String lock = '${_path}lock.svg';
  static const String sms = '${_path}sms.svg';
  static const String user = '${_path}user.svg';
  static const String add = '${_path}add.svg';
  static const String home = '${_path}home.svg';
  static const String profile = '${_path}profile.svg';
  static const String calendar= '${_path}calendar.svg';
  static const String building = '${_path}building.svg';
  static const String clock = '${_path}clock.svg';
  static const String notification = '${_path}notification.svg';
  static const String search = '${_path}search.svg';
  static const String calendarSearch = '${_path}calendar_search.svg';
  static const String addStaff = '${_path}add_staff.svg';
  static const String danger = '${_path}danger.svg';
  static const String emoji = '${_path}emoji.svg';
  static const String laws = '${_path}laws.svg';
  static const String notificationSolid = '${_path}notification_solid.svg';
  static const String report = '${_path}report.svg';
  static const String edit = '${_path}edit.svg';
  static const String translate = '${_path}translate.svg';
  static const String judge = '${_path}judge.svg';
  static const String policy = '${_path}policy.svg';
  static const String smsTracking = '${_path}sms_tracking.svg';
  static const String logout = '${_path}logout.svg';
  static const String close = '${_path}close.svg';
  static const String notificationLogo = '${_path}notification_logo.svg';
  static const String attachSquare = '${_path}attach_square.svg';
  static const String departmentBackground = '${_path}department_background.svg';
  static const String filter = '${_path}filter.svg';
  static const String employeeBackground = '${_path}employee_background.svg';
  static const String setting = '${_path}setting.svg';
  static const String check = '${_path}check.svg';
  static const String messageEdit = '${_path}message_edit.svg';
  static const String userEdit = '${_path}user_edit.svg';
}
